### ISSUE TITLE
Configuration Options

### ISSUE THREAD

**Issue by sgratzl** [danlamanna/joist#21]
@brianhelba What configuration options should be necessary for the s3 widget app? I can think of a few:
- STS Credential duration (above)
- Upload ARN to assume
- A prefix in the bucket to store uploads

_Originally posted by @danlamanna in https://github.com/danlamanna/joist/pull/11_

**Comment by brianhelba** [comment]
Joist also needs:
* `AWS_REGION`
* `AWS_ACCESS_KEY_ID`
* `AWS_SECRET_ACCESS_KEY`
* `AWS_STORAGE_BUCKET_NAME`

although these are owned by `django-storages`

**Comment by brianhelba** [comment]
I'm not sure if we need to support configuration of "STS Credential duration" initially, unless we can think of a compelling reason that downstreams need to change it. I think we should just pick a sane value (probably somewhere in the range of 1 to 24 hours).

**Comment by brianhelba** [comment]
Joist doesn't strictly need "A prefix in the bucket to store uploads", but this does sound like a useful optional option (Joist should provide a default), since downstreams may want to share the same bucket with other content (especially since `django-storages` only supports attachment to a single bucket). This is related to #29.

**Comment by brianhelba** [comment]
Decision:
Joist settings:
* STS Credential duration (default: 12 hours)
* Upload ARN to assume (required)
* A prefix in the bucket to store uploads (default `''`)

Joist also needs with `django-storages`:
* `AWS_REGION`
* `AWS_ACCESS_KEY_ID`
* `AWS_SECRET_ACCESS_KEY`
* `AWS_STORAGE_BUCKET_NAME`
